server:
  port: 10010
spring:
  application:
    name: getaway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: userService #路由表示，必须唯一
          uri: lb://userService #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** #判断请求是否以/user开头

        - id: orderService
          uri: lb://orderService
          predicates:
            - Path=/order/**
      #default-filter可以给全局加入默认过滤器 只能填写参数 不能做业务过滤
      default-filters:
        - AddRequestHeader=Truth,ccccccxxxxxyyyy #进入网关后的请求添加请求头
      #全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许所有的来源跨域
            allowedMethods: #允许跨域的方法
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            maxAge: 360000 #这次跨域检测的有效期