feign:
  client:
    config:
      default:
        #        logger-level: full
        logger-level: none #最好是basic或者是none 这样性能会好一点 full太吃性能了
  httpclient: #使用httpClient去优化远程访问，要在pom文件中导入对应的包 百度
    enabled: true
    max-connections: 200
    max-connections-per-route: 50